=== forkear/bfactory/src/bfactory/inputs/manifest.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://raw.githubusercontent.com/forkear/bfactory/main/src/bfactory/inputs/manifest.schema.json",
    "title": "bfactory Manifest", 
    "description": "bfactory manifest",
    "type": "object",
    "properties": {
      "name": {
        "description": "The name of your backend",
        "type": "string"
      },
      "version": {
        "description": "The version of your backend",
        "type": "string"
      },
      "auth":{
        "description": "the type of auth to use jwt/token",
        "enum": ["jwt", "token"]
      },
      
      "database":{
        
        "type":"object",
        
        "properties": {
        
          "type": { 
            "descripcion": "The type of database: sqlite | postgres",
            "enum": ["sqlite", "postgres"]
          },
          "name": { 
            "descripcion": "The name of the database ej: database.sqlite",
            "type": "string" 
          },
          "username": { 
            "type": "string" 
          },
          "password": { 
            "type": "string" 
          },
          "host": { 
            "type": "string" 
          },
          "port": { 
            "type": "string" 
          }
        },

        "anyOf": [
          {
            "properties": {
              "type": { "const": "sqlite" }
            },
            "required": ["name"]
          },
          {
            "properties": {
              "type": { "const": "postgres" }
            },
            "required": ["name", "username", "password", "host", "port"]
          }
         
        ]
        
      },

      "schema":{

        "description": "The model",
        
        "type": "array",
        "items": {
          
          "type":"object",
          "properties": {
            "name":{
              "description": "The model name",
              "type":"string"
            },
            "attrs":{
              "description": "The model attributes",
              "type": "array",
              "items": {
                  "type":"object",
                  "properties": {
                    "name": { 
                      "type": "string" 
                    },
                    "type": { 
                      "enum": [ "str", "bool", "User", "fk", "user","owner", "int", "pint", "decimal", "datetime","date" ] 
                    },
                    "req": { 
                      "type": "boolean" 
                    },
                    "default": { 
                      "type": [ "string", "boolean" ] 
                    },
                    "fk": {
                      "type":"string"
                    },
                    "auto_now":{
                      "type":"boolean"
                    }
                  },
                  "required": [ "name", "type", "req" ],

                  
                  "allOf": [ 
                    {
                    "if": {
                        "properties": {
                          "type": {"const":"fk"}
                        }
                    },
                    "then":{
                      "required": ["fk"]
                    }
                  },
                  {
                    "if": {
                        "properties": {
                          "type": {"const":"date"}
                        }
                    },
                    "then":{
                      "required": ["auto_now"]
                    }
                  },
                  {
                    "if": {
                        "properties": {
                          "type": {"const":"datetime"}
                        }
                    },
                    "then":{
                      "required": ["auto_now"]
                    }
                  }

                ]


                  

              }
            }
          },
          "required": [ "name", "attrs" ]
        }
      }

    },
    "required": [ "name", "version", "auth", "database"]
  }

=== forkear/bfactory/src/bfactory/tests/manifest_test.json
{
    "name":"Todo App",
    "version": "1",
    "auth": "jwt",
    
    "database":{
        "type":"sqlite",
        "name":"database.sqlite",
        "username":"",
        "password":"",
        "host":"",
        "port":""        
    },
    "schema":
        [
            {   
                "name":"Tarea",
                "attrs":[
                    {
                        "name":"descripcion",
                        "type":"str",
                        "req":true,
                        "default":""
                    },
                    {
                        "name":"realizada",
                        "type":"bool",
                        "req":false,
                        "default":false
                    },
                    {
                        "name":"usuario",
                        "type":"owner",
                        "req":true,
                        "default":""
                    }
                ]
            }
        ]
}

=== forkear/bfactory/tests/manifest_test.json
{
    "name":"Todo App",
    "version": "1",
    "auth": "jwt",
    
    "database":{
        "type":"sqlite",
        "name":"database.sqlite",
        "username":"",
        "password":"",
        "host":"",
        "port":""        
    },
    "schema":
        [
            {   
                "name":"Tarea",
                "perm":"700",
                "attrs":[
                    {
                        "name":"descripcion",
                        "type":"str",
                        "req":true,
                        "default":""
                    },
                    {
                        "name":"realizada",
                        "type":"bool",
                        "req":false,
                        "default":false
                    },
                    {
                        "name":"owner",
                        "type":"User",
                        "req":true,
                        "default":""
                    }
                ]
            }
        ]
}
